CREATE PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@GATEID AS INT,
@IOTYPE AS VARCHAR(1)
AS 
BEGIN
DECLARE @WORKERNAME AS VARCHAR(50)
DECLARE @WORKERID AS INT
SELECT @WORKERNAME =WORKERNAME,@WORKERID=ID FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE
	IF @WORKERID IS NULL
		BEGIN
			RAISERROR('KULLANICI TANIMLI BİR KULLANICI DEĞİLDİR.',16,1)
			RETURN
		END 
DECLARE @LASTIO AS VARCHAR(1)
SELECT TOP 1 @LASTIO=IOTYPE FROM WORKERTRANSACTIONS
WHERE WORKERID=@WORKERID AND DATE >= CONVERT(DATE,GETDATE())
ORDER BY DATE DESC
	IF @LASTIO=@IOTYPE
		BEGIN
			IF @IOTYPE='G'
				BEGIN
					RAISERROR('KULLANICI ZATEN İÇERİDEDİR',16,1)
					RETURN
				END
			IF @IOTYPE='C'
				BEGIN
					RAISERROR('KULLANICI ZATEN DISARIDADIR',16,1)
					RETURN
				END
	END
INSERT INTO WORKERTRANSACTIONS ([WORKERID], [DATE], [IOTYPE], [GATEID])
VALUES(@WORKERID,@DATE,@IOTYPE,@GATEID)
SELECT @WORKERNAME AS WORKERNAME,@DATE AS DATE ,@IOTYPE AS IOTYPE,@GATEID AS GATEID
END



